# Dependencies
# markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data","strikethrough"]
  parse_block_html: true
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'LIVE+CODE'
tagline:          'Tales of a traveling programmer'
description:      '{ <br>  "name":"Matteo",<br>  "surname":"Sandrin",<br>  "mainly":"programmer",<br>  "also":"traveler"<br>}'
url:              http://livepluscode.com
baseurl:          /

author:
  name:           'Matteo Sandin'

paginate:         5
