# Dependencies
# markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data","strikethrough"]
  parse_block_html: true
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'LIVE+CODE'
tagline:          'Tales of a traveling programmer'
description:      '/home/matteosandrin/stuff'
url:              http://livepluscode.com
baseurl:          /

author:
  name:           'Matteo Sandin'

paginate:         5
gems: ['jekyll-paginate']