# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'live+code'
tagline:          'Tales of a traveling programmer'
description:      '{ <br>  "name":"Matteo",<br>  "surname":"Sandrin",<br>  "mainly":"programmer",<br>  "also":"traveler"<br>}'
url:              http://livepluscode.com
baseurl:          /

author:
  name:           'Matteo Sandin'

paginate:         5
